spring.application.name=site
server.port=${PORT:8080}
#server.port=8081
#server.address=0.0.0.0


#--------------------------Database---------------------------------------------------------------------------------------------------------------------------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#spring.datasource.url=jdbc:postgresql://dpg-d84kcvojs32c739tfi3g-a.oregon-postgres.render.com/sitemanagement
#spring.datasource.username=sitemanagement_user
#spring.datasource.password=lKYGp5DSJobtt2EyVVczO6FtFYeCT5OQ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------


#----------------------------Security-------------------------------------------------------------------------------------------------------------------------
app.jwt.secret=AbhayManagementSystemSuperSecretJwtKey2026SecureKey
app.jwt.expiration-ms=86400000
#-----------------------------------------------------------------------------------------------------------------------------------------------------------



lgging.level=DEBUG
